// <auto-generated />
using System;
using MONKEY5.DataAccessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MONKEY5.BusinessObjects.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("ServiceEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ServiceStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ServiceUnitAmount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<float?>("TotalPrice")
                        .HasColumnType("real");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = new Guid("60000000-0000-0000-0000-000000000001"),
                            BookingDateTime = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Note = "Please focus on kitchen and bathroom cleaning. Customer has a cat, so be careful when entering.",
                            ServiceEndTime = new DateTime(2025, 3, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ServiceStartTime = new DateTime(2025, 3, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            ServiceUnitAmount = 3,
                            StaffId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Status = 3,
                            TotalPrice = 270000f
                        },
                        new
                        {
                            BookingId = new Guid("60000000-0000-0000-0000-000000000002"),
                            BookingDateTime = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Note = "Child is 5 years old and has homework to complete. Allergic to peanuts.",
                            ServiceEndTime = new DateTime(2025, 3, 4, 18, 0, 0, 0, DateTimeKind.Utc),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002"),
                            ServiceStartTime = new DateTime(2025, 3, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            ServiceUnitAmount = 4,
                            StaffId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Status = 3,
                            TotalPrice = 600000f
                        },
                        new
                        {
                            BookingId = new Guid("60000000-0000-0000-0000-000000000003"),
                            BookingDateTime = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Note = "Family prefers vegetarian dishes. Please use less spicy ingredients.",
                            ServiceEndTime = new DateTime(2025, 3, 5, 18, 0, 0, 0, DateTimeKind.Utc),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004"),
                            ServiceStartTime = new DateTime(2025, 3, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            ServiceUnitAmount = 5,
                            StaffId = new Guid("50000000-0000-0000-0000-000000000005"),
                            Status = 3,
                            TotalPrice = 400000f
                        },
                        new
                        {
                            BookingId = new Guid("60000000-0000-0000-0000-000000000004"),
                            BookingDateTime = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Note = "Deep cleaning needed for living room. Customer will provide special cleaning products for wooden furniture.",
                            ServiceEndTime = new DateTime(2025, 3, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ServiceStartTime = new DateTime(2025, 3, 6, 7, 0, 0, 0, DateTimeKind.Utc),
                            ServiceUnitAmount = 4,
                            StaffId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Status = 1,
                            TotalPrice = 360000f
                        },
                        new
                        {
                            BookingId = new Guid("60000000-0000-0000-0000-000000000005"),
                            BookingDateTime = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Note = "Two children ages 3 and 6. The older child has online classes from 9-10 AM. Both children need lunch prepared.",
                            ServiceEndTime = new DateTime(2025, 3, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003"),
                            ServiceStartTime = new DateTime(2025, 3, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            ServiceUnitAmount = 5,
                            StaffId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Status = 1,
                            TotalPrice = 1000000f
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.CompletionReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReportDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportText")
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("CompletionReports");

                    b.HasData(
                        new
                        {
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            BookingId = new Guid("60000000-0000-0000-0000-000000000001"),
                            ReportDateTime = new DateTime(2025, 3, 3, 13, 15, 0, 0, DateTimeKind.Utc),
                            ReportText = "Cleaned living room, kitchen, 2 bathrooms, and 3 bedrooms. All surfaces dusted and floors mopped."
                        },
                        new
                        {
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            BookingId = new Guid("60000000-0000-0000-0000-000000000002"),
                            ReportDateTime = new DateTime(2025, 3, 4, 18, 20, 0, 0, DateTimeKind.Utc),
                            ReportText = "Took care of the child, prepared lunch, helped with homework, and played educational games."
                        },
                        new
                        {
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            BookingId = new Guid("60000000-0000-0000-0000-000000000003"),
                            ReportDateTime = new DateTime(2025, 3, 5, 18, 10, 0, 0, DateTimeKind.Utc),
                            ReportText = "Prepared 5 dishes: spring rolls, pho, grilled chicken, stir-fried vegetables, and mango sticky rice for dessert."
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.LeaveRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaveEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaveReasons")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LeaveStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("RequestId");

                    b.HasIndex("StaffId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            RequestId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            LeaveEnd = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveReasons = "Family vacation planned months in advance.",
                            LeaveStart = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RequestId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            LeaveEnd = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveReasons = "Medical appointment and recovery.",
                            LeaveStart = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = new Guid("50000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RequestId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            LeaveEnd = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveReasons = "Professional development course on advanced culinary techniques.",
                            LeaveStart = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = new Guid("50000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Address = "123 Nguyen Hue Street",
                            City = "Ho Chi Minh City",
                            Country = "Vietnam",
                            PostalCode = "70000"
                        },
                        new
                        {
                            LocationId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Address = "456 Le Loi Street",
                            City = "Hanoi",
                            Country = "Vietnam",
                            PostalCode = "10000"
                        },
                        new
                        {
                            LocationId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Address = "789 Tran Hung Dao Street",
                            City = "Da Nang",
                            Country = "Vietnam",
                            PostalCode = "50000"
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaymentCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaymentPaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Amount = 270000m,
                            BookingId = new Guid("60000000-0000-0000-0000-000000000001"),
                            PaymentCreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 2,
                            PaymentPaidAt = new DateTime(2025, 3, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = 1
                        },
                        new
                        {
                            PaymentId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Amount = 600000m,
                            BookingId = new Guid("60000000-0000-0000-0000-000000000002"),
                            PaymentCreatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 3,
                            PaymentPaidAt = new DateTime(2025, 3, 4, 18, 30, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = 1
                        },
                        new
                        {
                            PaymentId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Amount = 400000m,
                            BookingId = new Guid("60000000-0000-0000-0000-000000000003"),
                            PaymentCreatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 1,
                            PaymentPaidAt = new DateTime(2025, 3, 4, 2, 0, 0, 0, DateTimeKind.Utc),
                            PaymentStatus = 1
                        },
                        new
                        {
                            PaymentId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Amount = 360000m,
                            BookingId = new Guid("60000000-0000-0000-0000-000000000004"),
                            PaymentCreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 2,
                            PaymentStatus = 0
                        },
                        new
                        {
                            PaymentId = new Guid("70000000-0000-0000-0000-000000000005"),
                            Amount = 1000000m,
                            BookingId = new Guid("60000000-0000-0000-0000-000000000005"),
                            PaymentCreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = 1,
                            PaymentStatus = 0
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Refund", b =>
                {
                    b.Property<Guid>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RefundDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text");

                    b.HasKey("RefundId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("Refunds");

                    b.HasData(
                        new
                        {
                            RefundId = new Guid("90000000-0000-0000-0000-000000000001"),
                            PaymentId = new Guid("70000000-0000-0000-0000-000000000003"),
                            RefundAmount = 100000m,
                            RefundDateTime = new DateTime(2025, 3, 5, 2, 0, 0, 0, DateTimeKind.Utc),
                            RefundReason = "One dish was not prepared as requested"
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.ReportImage", b =>
                {
                    b.Property<Guid>("ReportImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("ReportImageId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportImages");

                    b.HasData(
                        new
                        {
                            ReportImageId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            ImagePath = "cleaning_living_room.jpg",
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ReportImageId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            ImagePath = "cleaning_kitchen.jpg",
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ReportImageId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            ImagePath = "childcare_lunch.jpg",
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            ReportImageId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            ImagePath = "cooking_spring_rolls.jpg",
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            ReportImageId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            ImagePath = "cooking_pho.jpg",
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            ReportImageId = new Guid("b0000000-0000-0000-0000-000000000006"),
                            ImagePath = "cooking_dessert.jpg",
                            ReportId = new Guid("a0000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("RatingStar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReviewId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = new Guid("80000000-0000-0000-0000-000000000001"),
                            BookingId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Comment = "Excellent cleaning service, very thorough and professional!",
                            RatingStar = 5,
                            ReviewDateTime = new DateTime(2025, 3, 3, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ReviewId = new Guid("80000000-0000-0000-0000-000000000002"),
                            BookingId = new Guid("60000000-0000-0000-0000-000000000002"),
                            Comment = "Great childcare service, my child was very happy.",
                            RatingStar = 4,
                            ReviewDateTime = new DateTime(2025, 3, 4, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ReviewId = new Guid("80000000-0000-0000-0000-000000000003"),
                            BookingId = new Guid("60000000-0000-0000-0000-000000000003"),
                            Comment = "Amazing cooking! The dishes were delicious and beautifully presented.",
                            RatingStar = 5,
                            ReviewDateTime = new DateTime(2025, 3, 5, 19, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UnitType")
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "Professional home cleaning service",
                            ServiceName = "Cleaning",
                            UnitPrice = 90000m,
                            UnitType = "hour"
                        },
                        new
                        {
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Description = "Childcare service for one child",
                            ServiceName = "Child care (1 child)",
                            UnitPrice = 150000m,
                            UnitType = "hour"
                        },
                        new
                        {
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Description = "Childcare service for two children",
                            ServiceName = "Child care (2 children)",
                            UnitPrice = 200000m,
                            UnitType = "hour"
                        },
                        new
                        {
                            ServiceId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Description = "Professional cooking service",
                            ServiceName = "Cooking",
                            UnitPrice = 80000m,
                            UnitType = "dish"
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IdNumber")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Customer", b =>
                {
                    b.HasBaseType("MONKEY5.BusinessObjects.User");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("LocationId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("40000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenvana@example.com",
                            FullName = "Nguyen Van A",
                            Gender = "Male",
                            IdNumber = "123456789012",
                            PasswordHash = "6EWPhMIzswfhpCXVNXGU9A==./5M/zflau4lbdKWoCCRNjGBIl8K90e9SwB2UaVtsQNQ=",
                            PhoneNumber = "0123456781",
                            Role = "Customer",
                            LocationId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RegistrationDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("40000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranthib@example.com",
                            FullName = "Tran Thi B",
                            Gender = "Female",
                            IdNumber = "234567890123",
                            PasswordHash = "SBX1L2Ud1uZaja7DeEuxBw==.wQq3Hswz6WvId/RQiGf6fEHsqI1AUoimCSVRgLKwZVs=",
                            PhoneNumber = "0123456782",
                            Role = "Customer",
                            LocationId = new Guid("10000000-0000-0000-0000-000000000002"),
                            RegistrationDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("40000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "levanc@example.com",
                            FullName = "Le Van C",
                            Gender = "Male",
                            IdNumber = "345678901234",
                            PasswordHash = "vQ47gUxNoa1Wy6AuKG6kvA==.Gm2Yqc6AANIzfr5AlJYWPqjAi56B+Yo6TcMtDBL7fGA=",
                            PhoneNumber = "0123456783",
                            Role = "Customer",
                            LocationId = new Guid("10000000-0000-0000-0000-000000000003"),
                            RegistrationDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Manager", b =>
                {
                    b.HasBaseType("MONKEY5.BusinessObjects.User");

                    b.ToTable("Managers", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("30000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@monkey5.com",
                            FullName = "Admin User",
                            Gender = "Male",
                            IdNumber = "123456789",
                            PasswordHash = "xoEkkHvDXQdo+g+sGMCwWw==.7Ds+rL90/t6JQ7X1ukmDAzYwQRyQ9DkEqmEkpsGPfDk=",
                            PhoneNumber = "0123456789",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Staff", b =>
                {
                    b.HasBaseType("MONKEY5.BusinessObjects.User");

                    b.Property<double>("AvgRating")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ToTable("Staffs", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("50000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1992, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamthid@example.com",
                            FullName = "Pham Thi D",
                            Gender = "Female",
                            IdNumber = "456789012345",
                            PasswordHash = "384zy+tSBIrwPPt/kk2Jpg==.2jyJ8MhzvG1U7JIo+TR8wPPsyh6E6Gaw6N8cO37PgDo=",
                            PhoneNumber = "0234567891",
                            Role = "Staff",
                            AvgRating = 4.5,
                            Status = 0
                        },
                        new
                        {
                            UserId = new Guid("50000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1991, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoangvane@example.com",
                            FullName = "Hoang Van E",
                            Gender = "Male",
                            IdNumber = "567890123456",
                            PasswordHash = "Ci1up0LXTLHzel6z2zmJbA==.Yl/hMB1RjgkYexu5dXooq/ki7/Sc9FXuVgcw4MenWhs=",
                            PhoneNumber = "0234567892",
                            Role = "Staff",
                            AvgRating = 4.2000000000000002,
                            Status = 0
                        },
                        new
                        {
                            UserId = new Guid("50000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1989, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyenthif@example.com",
                            FullName = "Nguyen Thi F",
                            Gender = "Female",
                            IdNumber = "678901234567",
                            PasswordHash = "JDTicAJpOxKDlrQAA/7U1g==.73lcm/Ot50Nuk82BcII2ulQ/jyChtocmVnIrEzo2b8k=",
                            PhoneNumber = "0234567893",
                            Role = "Staff",
                            AvgRating = 4.7999999999999998,
                            Status = 0
                        },
                        new
                        {
                            UserId = new Guid("50000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1993, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tranvang@example.com",
                            FullName = "Tran Van G",
                            Gender = "Male",
                            IdNumber = "789012345678",
                            PasswordHash = "RRZMG7TF+irCimeegiUYSA==.bufpyO9z6S8jhEBoU/Q2bi9rWgmdsqDOPGjSHEgT7YA=",
                            PhoneNumber = "0234567894",
                            Role = "Staff",
                            AvgRating = 4.2999999999999998,
                            Status = 0
                        },
                        new
                        {
                            UserId = new Guid("50000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(1987, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lethih@example.com",
                            FullName = "Le Thi H",
                            Gender = "Female",
                            IdNumber = "890123456789",
                            PasswordHash = "T7JDiR3H/NvIMERM07a8MA==.18jZVTHSfl3fxjxZI75EJkqdczIQNG1vH2dq0UPijoU=",
                            PhoneNumber = "0234567895",
                            Role = "Staff",
                            AvgRating = 4.9000000000000004,
                            Status = 0
                        },
                        new
                        {
                            UserId = new Guid("50000000-0000-0000-0000-000000000006"),
                            DateOfBirth = new DateTime(1990, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "phamvani@example.com",
                            FullName = "Pham Van I",
                            Gender = "Male",
                            IdNumber = "901234567890",
                            PasswordHash = "hjbJp7T7XTCL+15d+gJVCw==.Y5YOmwy5LKq9xN2vZXXR3hYcxVQrkw4vngdPJ2LAuxM=",
                            PhoneNumber = "0234567896",
                            Role = "Staff",
                            AvgRating = 4.5999999999999996,
                            Status = 0
                        });
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Booking", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MONKEY5.BusinessObjects.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MONKEY5.BusinessObjects.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.CompletionReport", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Booking", "Booking")
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.CompletionReport", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.LeaveRequest", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Payment", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Booking", "Booking")
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Refund", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Payment", "Payment")
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.Refund", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.ReportImage", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.CompletionReport", "CompletionReport")
                        .WithMany("ReportImages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CompletionReport");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Review", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Booking", "Booking")
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Customer", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MONKEY5.BusinessObjects.User", null)
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Manager", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.User", null)
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.Manager", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.Staff", b =>
                {
                    b.HasOne("MONKEY5.BusinessObjects.User", null)
                        .WithOne()
                        .HasForeignKey("MONKEY5.BusinessObjects.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MONKEY5.BusinessObjects.CompletionReport", b =>
                {
                    b.Navigation("ReportImages");
                });
#pragma warning restore 612, 618
        }
    }
}
